name: foods_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  go_router: ^16.1.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  flutter_svg: ^2.2.0
  equatable: ^2.0.7
  cloud_firestore: ^6.0.0
  google_sign_in: ^7.1.1
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  flutter_gen_runner: ^5.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/fonts/

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true

