// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4hoUlprMyjEgG5znY-GaToqlIMAYCvHk',
    appId: '1:785258560356:web:2a9df4fb544490345f5871',
    messagingSenderId: '785258560356',
    projectId: 'foods-app-75f2f',
    authDomain: 'foods-app-75f2f.firebaseapp.com',
    storageBucket: 'foods-app-75f2f.firebasestorage.app',
    measurementId: 'G-D0MR1V9KRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGbwNfh3KRIYsLMClBu6sD1ZBzl-3BhbM',
    appId: '1:785258560356:android:ed6a3fe21d6fb8e85f5871',
    messagingSenderId: '785258560356',
    projectId: 'foods-app-75f2f',
    storageBucket: 'foods-app-75f2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr66NdLSL8_3K4YmBaunzGpilZ0QiByeI',
    appId: '1:785258560356:ios:ab32d5035a9255705f5871',
    messagingSenderId: '785258560356',
    projectId: 'foods-app-75f2f',
    storageBucket: 'foods-app-75f2f.firebasestorage.app',
    iosBundleId: 'com.example.foodsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr66NdLSL8_3K4YmBaunzGpilZ0QiByeI',
    appId: '1:785258560356:ios:ab32d5035a9255705f5871',
    messagingSenderId: '785258560356',
    projectId: 'foods-app-75f2f',
    storageBucket: 'foods-app-75f2f.firebasestorage.app',
    iosBundleId: 'com.example.foodsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4hoUlprMyjEgG5znY-GaToqlIMAYCvHk',
    appId: '1:785258560356:web:a2ba8939d2a06f155f5871',
    messagingSenderId: '785258560356',
    projectId: 'foods-app-75f2f',
    authDomain: 'foods-app-75f2f.firebaseapp.com',
    storageBucket: 'foods-app-75f2f.firebasestorage.app',
    measurementId: 'G-NNJ1S39Q97',
  );
}
